<?php

namespace App\Repository;

/**
 * CategoryNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryNewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLimit($order,$limit)
    {
        return $this->createQueryBuilder('c')
            ->select('c.name','c.urlSlug','c.title','c.id','c.subject')
            ->andWhere('c.displayStatus = :displayStatus')
            ->setParameter('displayStatus', 1)
            ->orderBy('c.'.$order, 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->expireQueryCache(true)
            ->useQueryCache(true)
//            ->useResultCache(true, 600)
            ->setResultCacheId('category××××news−×××−−×1')
            ->getResult();
    }
}
